site_name: WitsKit
site_description: Python toolkit for WITS (Wellsite Information Transfer Standard) data
site_url: https://github.com/yourusername/witskit
repo_url: https://github.com/yourusername/witskit
repo_name: yourusername/witskit

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [witskit]
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            show_bases: true
            docstring_style: google

nav:
  - Home: index.md
  - Installation: installation.md
  - User Guide:
    - Getting Started: guide/getting-started.md
    - CLI Usage: guide/cli-usage.md
    - WITS Format: guide/wits-format.md
  - API Reference:
    - Decoder: api/decoder.md
    - Models: api/models.md
    - Transport: api/transport.md
  - Development:
    - Contributing: development/contributing.md
    - Architecture: development/architecture.md

markdown_extensions:
  - tables
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
